# Generated by Django 6.0.2 on 2026-02-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_authenticated',
        ),
    ]
