# Generated by Django 6.0.2 on 2026-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpromotion',
            name='plan',
            field=models.CharField(choices=[('1m', '1 Month'), ('3m', '3 Months'), ('6m', '6 Months')], max_length=20),
        ),
    ]
