# Generated by Django 6.0.2 on 2026-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_store_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepromotion',
            name='plan',
            field=models.CharField(choices=[('spotlight', '1 Month'), ('featured', '3 Months'), ('premium', '6 Months')], max_length=20),
        ),
    ]
